
package com.playsafe.conversions.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.6
 * Thu Apr 30 17:55:51 IDT 2020
 * Generated source version: 3.3.6
 */

@XmlRootElement(name = "toKilometreResponse", namespace = "http://conversions.playsafe.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "toKilometreResponse", namespace = "http://conversions.playsafe.com/")

public class ToKilometreResponse {

    @XmlElement(name = "return")
    private double _return;

    public double getReturn() {
        return this._return;
    }

    public void setReturn(double new_return)  {
        this._return = new_return;
    }

}

